# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc
before_script:
  - apt update && apt -y install cmake git libgl-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libopengl0

stages:
  - build
  - test
  - release

build:
  stage: build
  script:
    - git submodule update --init --recursive
    - mkdir out && cd out 
    - cmake .. 
    - cmake --build . -j 8 --target I3T
    - cmake --build . -j 8 --target I3TTest
  artifacts:
    paths:
      - Binaries
    expire_in: 1 week
  cache:
    paths:
      - Binaries

# run tests using the binary built before
test:
  stage: test
  script:
    - Binaries/Debug/I3TTest

release:
  stage: release
  only:
    - master
  script:
    - mkdir relase-out && cd release-out
    - cmake -DCMAKE_BUILD_TYPE=ReleaseStandalone .. 
    - cmake --build . -j 8 --target I3T
  artifacts:
    paths:
      - Binaries/Release*
