image: cvutdcgi/i3t-ci

stages:
  - build
  - test
  - release

build:
  stage: build
  script:
    - mkdir out && cd out 
    - cmake .. 
    - cmake --build . -j 8 --target I3T I3TTest
  artifacts:
    paths:
      - Binaries
    expire_in: 1 week
  cache:
    paths:
      - Binaries
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

check format:
  stage: build
  script:
    - bash Scripts/CheckFormat.sh

# run tests using the binary built before
test:
  stage: test
  script:
    - Binaries/Debug/I3TTest

release:
  stage: release
  only:
    - master
  script:
    - mkdir relase-out && cd release-out
    - cmake -DCMAKE_BUILD_TYPE=ReleaseStandalone .. 
    - cmake --build . -j 8 --target I3T
  artifacts:
    paths:
      - Binaries/Release*
