#include "IconsFontAwesome6.h"

#include "IconsFontAwesome6_I3T.h"

#define ICON_I3T_NEW_FILE ICON_FA_FILE
#define ICON_I3T_OPEN_FILE ICON_FA_FOLDER_OPEN
#define ICON_I3T_CLOCK ICON_FA_CLOCK
#define ICON_I3T_SAVE ICON_FA_FLOPPY_DISK
#define ICON_I3T_EXIT ICON_FA_DOOR_OPEN
#define ICON_I3T_MODEL ICON_FA_CUBE
#define ICON_I3T_MODELS ICON_FA_CUBES
#define ICON_I3T_MODELS ICON_FA_CUBES
#define ICON_I3T_REFRESH ICON_FA_ARROWS_ROTATE
#define ICON_I3T_SCENE ICON_FA_MOUNTAIN_SUN
#define ICON_I3T_WORKSPACE ICON_FA_CIRCLE_NODES
#define ICON_I3T_DEBUG ICON_FA_BUG
#define ICON_I3T_HELP ICON_FA_CIRCLE_QUESTION
#define ICON_I3T_TUTORIAL ICON_FA_BOOK
#define ICON_I3T_CONSOLE ICON_FA_TERMINAL
#define ICON_I3T_LOG ICON_FA_FILE_LINES
#define ICON_I3T_HOME ICON_FA_HOUSE
#define ICON_I3T_MANIPULATOR ICON_FA_I3T_GIZMO
#define ICON_I3T_EARTH ICON_FA_EARTH_EUROPE
#define ICON_I3T_CAMERA ICON_FA_VIDEO
#define ICON_I3T_GRID ICON_FA_BORDER_ALL
#define ICON_I3T_FRUSTUM ICON_FA_I3T_FRUSTUM
#define ICON_I3T_SETTINGS ICON_FA_GEAR
#define ICON_I3T_WRENCH ICON_FA_WRENCH
#define ICON_I3T_STYLE ICON_FA_PAINTBRUSH
#define ICON_I3T_CHECK ICON_FA_CHECK
#define ICON_I3T_LANG ICON_FA_LANGUAGE
#define ICON_I3T_FILE_IMPORT ICON_FA_FILE_IMPORT
#define ICON_I3T_REF_SPACE ICON_FA_SOLAR_PANEL
#define ICON_I3T_TRACKING ICON_FA_CROSSHAIRS