FROM debian:bullseye-slim

RUN apt update && apt install -y \
    clang-format \
    cmake \
    git \
    g++ \
    make \
    libgl-dev \
    libopengl0 \
    libxrandr-dev \
    libxinerama-dev \
    libxcursor-dev \
    libxi-dev
