#include "IconsFontAwesome6.h"

#define ICON_I3T_NEW_FILE ICON_FA_FILE
#define ICON_I3T_OPEN_FILE ICON_FA_FOLDER_OPEN
#define ICON_I3T_CLOCK ICON_FA_CLOCK
#define ICON_I3T_SAVE ICON_FA_FLOPPY_DISK
#define ICON_I3T_EXIT ICON_FA_DOOR_OPEN
#define ICON_I3T_MODEL ICON_FA_CUBE
#define ICON_I3T_MODELS ICON_FA_CUBES
#define ICON_I3T_MODELS ICON_FA_CUBES
#define ICON_I3T_REFRESH ICON_FA_ARROWS_ROTATE
#define ICON_I3T_SCENE ICON_FA_MOUNTAIN_SUN
#define ICON_I3T_WORKSPACE ICON_FA_CIRCLE_NODES
#define ICON_I3T_DEBUG ICON_FA_BUG
#define ICON_I3T_HELP ICON_FA_CIRCLE_QUESTION
#define ICON_I3T_TUTORIAL ICON_FA_BOOK
#define ICON_I3T_CONSOLE ICON_FA_TERMINAL
#define ICON_I3T_LOG ICON_FA_FILE_LINES
#define ICON_I3T_HOME ICON_FA_HOUSE