name: Code Quality
on:
  pull_request:
    branches:
      - develop
      - master
    paths:
      - '.github/workflows/code-quality.yml'
      - 'Source/**'
      - 'Scripts/**'
      - 'Test/**'
      - '.clang-format'
      - '.clang-tidy'
      - 'CMakeLists.txt'

jobs:
  check-format:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run clang-format check
        run: |
          bash Scripts/CheckFormat.sh
  test:
    strategy:
      matrix:
        kind: [ 'Linux', 'Windows' ]
        include:
          - kind: 'Linux'
            os: ubuntu-latest
          - kind: 'Windows'
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Build tests
        uses: ./.github/actions/build
        with:
          target: 'I3TTest'
          cmake_build_type: 'Debug'
          jobs: '2'

      - name: Run tests with xvfb
        if: matrix.kind == 'Linux'
        run: |
          xvfb-run Binaries/Debug/I3TTest

      - name: Run tests
        if: matrix.kind == 'Windows'
        run: |
          Binaries/Debug/I3TTest